import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { ResultsDisplay } from './ResultsDisplay';

describe('ResultsDisplay', () => {
     it('should display the prediction as large text', () => {
          render(<ResultsDisplay prediction="Very Mild Dementia" confidence={85.5} />);

          const predictionElement = screen.getByTestId('prediction-result');
          expect(predictionElement).toHaveTextContent('Prediction: Very Mild Dementia');
          // Responsive classes: text-xl on mobile, scales up to text-3xl on desktop
          expect(predictionElement).toHaveClass('font-bold');
     });

     it('should display the confidence bar with correct percentage', () => {
          render(<ResultsDisplay prediction="Mild Dementia" confidence={72.3} />);

          const percentageText = screen.getByTestId('confidence-percentage');
          expect(percentageText).toHaveTextContent('72.3%');
     });

     it('should display the default disclaimer text', () => {
          render(<ResultsDisplay prediction="Non-Demented" confidence={95} />);

          const disclaimer = screen.getByTestId('disclaimer-text');
          expect(disclaimer).toHaveTextContent('This result is generated by AI and is not a medical diagnosis');
          expect(disclaimer).toHaveTextContent('Please consult a neurologist');
     });

     it('should display custom disclaimer when provided', () => {
          const customDisclaimer = 'Custom disclaimer text for testing';
          render(
               <ResultsDisplay
                    prediction="Moderate Dementia"
                    confidence={60}
                    disclaimer={customDisclaimer}
               />
          );

          const disclaimer = screen.getByTestId('disclaimer-text');
          expect(disclaimer).toHaveTextContent(customDisclaimer);
     });
});
