import { ConfidenceBar } from '../ConfidenceBar';

interface ResultsDisplayProps {
     prediction: string;
     confidence: number;
     disclaimer?: string;
}

const DEFAULT_DISCLAIMER = "This result is generated by AI and is not a medical diagnosis. Please consult a neurologist.";

export function ResultsDisplay({
     prediction,
     confidence,
     disclaimer = DEFAULT_DISCLAIMER
}: ResultsDisplayProps) {
     return (
          <div
               className="bg-white rounded-xl shadow-lg p-4 md:p-6 lg:p-8 space-y-4 md:space-y-6"
               role="region"
               aria-label="Analysis results"
          >
               {/* Prediction result */}
               <div className="text-center">
                    <h2 className="text-xs md:text-sm font-medium text-gray-500 uppercase tracking-wide mb-1 md:mb-2">
                         Analysis Result
                    </h2>
                    <p
                         className="text-xl sm:text-2xl md:text-3xl font-bold text-gray-900 break-words"
                         data-testid="prediction-result"
                    >
                         Prediction: {prediction}
                    </p>
               </div>

               {/* Confidence bar */}
               <div className="pt-2 md:pt-4">
                    <ConfidenceBar
                         percentage={confidence}
                         label="Confidence Level"
                    />
               </div>

               {/* Disclaimer */}
               <div
                    className="mt-4 md:mt-6 p-3 md:p-4 bg-amber-50 border border-amber-200 rounded-lg"
                    role="alert"
               >
                    <p
                         className="text-xs md:text-sm text-amber-800"
                         data-testid="disclaimer-text"
                    >
                         ⚠️ {disclaimer}
                    </p>
               </div>
          </div>
     );
}
